name: The Paircast
url: http://www.thepaircast.com
description: Pair programming streamed live

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
